---
title: "project"
author: "Ankit Phaterpekar"
date: "March 24, 2018"
output: html_document
---


```{r}
library(insuranceData)
data(dataCar)
library(dplyr)

dataCar <- dataCar %>% filter(claimcst0 > 0.0)
```

```{r}
summary(dataCar)
m1 <- lm(log(claimcst0) ~ veh_value + veh_body + veh_age + gender + area + agecat, data=dataCar)
summary(m1)
```

# Build Dataset
```{r}
set.seed(100)
n <- 100
veh_value <- sample(10:100, n, replace=T)
hist(veh_value)

gender <- rbinom(n, 1, .5)
veh_age <- sample(0:30, n, replace=T)
age_cat <- sample(25:55, n, replace=T)
area <- sample(0:2, n, replace=T)

b0 <- 10
b1 <- 5
b2 <- 3.5
b3 <- 2
b4 <- 0.1

bArea0 <- 1
bArea1 <- 2
bArea2 <- 3

e <- rnorm(n, mean=0, sd=10)
y <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e

df <- data.frame(y, veh_value, gender, veh_age, age_cat, area)
df[, 'area'] <-  as.factor(df[, 'area'])
df[, 'gender'] <- as.factor(df[, 'gender'])

#add area as categorical and keep age as numeric
```




Standard Model
==============
```{r}
model <- lm(y ~ veh_value + gender + veh_age + age_cat + area, data=df)
summary(model)
plot(model)


library(ggplot2)
ggplot(df, aes(x=veh_value, y= y)) + 
   geom_point(color='#2980B9', size = 2)+
  stat_smooth(method=lm, color='red')

# plot(df$y, df$veh_value)
# 
# plot(model2$fitted.values, df$veh_value)
# plot(df$y, df$veh_value)
# abline(lm(y ~ veh_value, data=df),col = "red",lwd=3.5,cex= 5)
# 
# library(ggplot2)
# ggplot(df, aes(x=veh_value2, y= y)) + 
#   geom_smooth(method=lm, color='red')
# ?ggplot
# 
# ?geom_smooth()
```

# Model with Outliers/Influential Observations
```{r}
df$veh_value2 <- df$veh_value
df$y2 <- df$y
df$y3 <- df$y

df$veh_value2[df$veh_value > 94 & df$veh_value <= 95] <- 155
df$veh_value2[df$veh_value > 95 & df$veh_value <= 97] <- 160
df$veh_value2[df$veh_value > 97 & df$veh_value <= 99] <- 180
df$veh_value2[df$veh_value > 99 & df$veh_value <= 100] <- 200
#which(df$veh_value > 95 & df$veh_value <= 97)
#df[c(34,63,74),]
df$y2[63]<- 230

model2 <- lm(y2 ~ veh_value2 + gender + veh_age + age_cat + area, data=df)
summary(model2)
plot(model2)

plot(model2$fitted.values, df$veh_value2)

boxplot(df$veh_value2)
library(ggplot2)
ggplot(df, aes(x=veh_value2, y= y2)) + 
  geom_point(color='#2980B9', size = 2) + 
  geom_smooth(method=lm, color='#2C3E50',se = TRUE)
  

plot(df$veh_value2,model2$residuals)

```

# Model with Outliers but no Influential Observations
```{r}
df$veh_value3 <- df$veh_value
df$veh_value3[df$veh_value > 94 & df$veh_value <= 100] <- 180

#which(df$veh_value > 94 & df$veh_value <= 100)
df$y3[c(34,63,74,39,84)]
#df$y[c(34)]<- 230
df$y3[c(34,63)]<- 870
df$y3[c(74,39,84)]<- 920

model3 <- lm(y3 ~ veh_value3 + gender + veh_age + age_cat + area, data=df)
summary(model3)
plot(model3)

plot(model3$fitted.values, df$veh_value3)

boxplot(df$veh_value3)
library(ggplot2)
ggplot(df, aes(x=veh_value3, y= y3)) + 
  geom_point(color='#2980B9', size = 4) + 
  geom_smooth(method=lm, color='#2C3E50',se = TRUE)

plot(df$veh_value3,model3$residuals)
df$y3[c(74,39,84,34,63)]
```




#  Non-Normal Distribution 
```{r}
set.seed(1113)
n <- 10000
veh_value <- sample(10:100, n, replace=T)
gender <- rbinom(n, 1, .5)
veh_age <- sample(0:30, n, replace=T)
age_cat <- sample(25:55, n, replace=T)
area <- sample(0:2, n, replace=T)

b0 <- 10
b1 <- 5
b2 <- 3.5
b3 <- 2
b4 <- 0.1

bArea0 <- 1
bArea1 <- 2
bArea2 <- 3

#exp(1)

#y <- rpois(n,10)
e <- rnorm(n, mean=0, sd=10.)

y <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e

#head(y)
y <- y^2

df <- data.frame(y, veh_value, gender, veh_age, age_cat, area)
df[, 'area'] <-  as.factor(df[, 'area'])
df[, 'gender'] <- as.factor(df[, 'gender'])

model <- lm(y ~ veh_value + gender + veh_age + age_cat + area, data=df)
summary(model)
plot(model)
hist(model$residuals)
hist(df$y, main = "Response Variable Y - Not normally distributed",xlab='Response Variable')
```

Square root transformation using box-cox
```{r}
library(MASS)
bc <- boxcox(y ~ veh_value + gender + veh_age + age_cat + area,data=df)

(lambda <- bc$x[which.max(bc$y)])
# 
y_2 <- lm(y^0.5 ~ veh_value + gender + veh_age + age_cat + area, data=df)
summary(y_2)
plot(y_2)
hist(y_2$residuals)


(trans <- bc$x[which.max(bc$y)])
#[1] 0.4242424
# re-run with transformation
mnew <- lm(((y^trans-1)/trans) ~  veh_value + gender + veh_age + age_cat + area, data=df)
summary(mnew)
plot(mnew)
```

# Y(inverse) transformation
```{r}
set.seed(1113)
n <- 10000
veh_value <- sample(10:100, n, replace=T)
gender <- rbinom(n, 1, .5)
veh_age <- sample(0:30, n, replace=T)
age_cat <- sample(25:55, n, replace=T)
area <- sample(0:2, n, replace=T)

b0 <- 10
b1 <- 5
b2 <- 3.5
b3 <- 2
b4 <- 0.1

bArea0 <- 1
bArea1 <- 2
bArea2 <- 3

#exp(1)

#y <- rpois(n,10)
e <- rnorm(n, mean=0, sd=10.)

y <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e

# head(y)
# y[1]
# log(exp(182.8027))

y <- 1/y

df <- data.frame(y, veh_value, gender, veh_age, age_cat, area)
df[, 'area'] <-  as.factor(df[, 'area'])
df[, 'gender'] <- as.factor(df[, 'gender'])

model <- lm(y ~ veh_value + gender + veh_age + age_cat + area, data=df)
summary(model)
plot(model)
hist(model$residuals)


```
```{r}
library(MASS)
bc <- boxcox(y ~ veh_value + gender + veh_age + age_cat + area,data=df)

(lambda <- bc$x[which.max(bc$y)])
# 
# y_2 <- lm(y^0.5 ~ veh_value + gender + veh_age + age_cat + area, data=df)
# summary(y_2)
# plot(y_2)
# hist(y_2$residuals)


(trans <- bc$x[which.max(bc$y)])
#[1] 0.4242424
# re-run with transformation
mnew <- lm(((y^trans-1)/trans) ~  veh_value + gender + veh_age + age_cat + area, data=df)
summary(mnew)
plot(mnew)
```



-----------------------------### END ###-------------------------------------

<!-- Correlated Predictors -->
<!-- ===================== -->
<!-- ```{r} -->
<!-- cond <- (df$veh_age > df$age_cat - 27) & (df$veh_age < df$age_cat - 23) -->
<!-- df_filt <- df[cond, ] -->
<!-- model <- lm(y ~ veh_value + gender + veh_age + age_cat + area, df_filt) -->
<!-- summary(model) -->
<!-- plot(model) -->
<!-- library(car) -->
<!-- vif(model) -->
<!-- ``` -->


<!-- Outliers/ Non-Normal Errors -->
<!-- ```{r} -->
<!-- set.seed(101) -->
<!-- n <- 100000 -->
<!-- veh_value <- sample(10:100, n, replace=T) -->
<!-- gender <- rbinom(n, 1, .5) -->
<!-- veh_age <- sample(0:30, n, replace=T) -->
<!-- age_cat <- sample(25:55, n, replace=T) -->
<!-- area <- sample(0:2, n, replace=T) -->

<!-- b0 <- 10 -->
<!-- b1 <- 5 -->
<!-- b2 <- 3.5 -->
<!-- b3 <- 2 -->
<!-- b4 <- 0.1 -->

<!-- bArea0 <- 1 -->
<!-- bArea1 <- 2 -->
<!-- bArea2 <- 3 -->

<!-- e <- rnorm(n-500, mean=0, sd=10.) -->
<!-- summary(e) -->
<!-- length(e) -->

<!-- e_500 <- runif(500, min = 5, max = 200) -->
<!-- summary(e_500) -->

<!-- e_c <- c(e,e_500) -->
<!-- length(e_c) -->
<!-- summary(e_c) -->
<!-- summary(e) -->

<!-- # e <- rnorm(n, mean=0, sd=10.) -->
<!-- # y <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e -->
<!-- #  -->
<!-- # df <- data.frame(y, veh_value, gender, veh_age, age_cat, area) -->
<!-- # df[, 'area'] <-  as.factor(df[, 'area']) -->
<!-- # df[, 'gender'] <- as.factor(df[, 'gender']) -->

<!-- y <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e_c -->

<!-- df_outliers <- data.frame(y, veh_value, gender, veh_age, age_cat, area) -->
<!-- # df_outliers[, 'area'] <-  as.factor(df[, 'area']) -->
<!-- # df_outliers[, 'gender'] <- as.factor(df[, 'gender']) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- model_outliers <- lm(y ~ veh_value + gender + veh_age + age_cat + area, data=df_outliers) -->
<!-- summary(model_outliers) -->
<!-- plot(model_outliers) -->

<!-- plot(model_outliers$residuals,df_outliers$veh_value) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- summary(model) -->

<!-- ``` -->


<!-- Non-normal Errors -->

<!-- ```{r} -->
<!-- set.seed(102) -->
<!-- n <- 100000 -->
<!-- veh_value <- sample(10:100, n, replace=T) -->
<!-- gender <- rbinom(n, 1, .5) -->
<!-- veh_age <- sample(0:30, n, replace=T) -->
<!-- age_cat <- sample(25:55, n, replace=T) -->
<!-- area <- sample(0:2, n, replace=T) -->

<!-- b0 <- 10 -->
<!-- b1 <- 5 -->
<!-- b2 <- 3.5 -->
<!-- b3 <- 2 -->
<!-- b4 <- 0.1 -->

<!-- bArea0 <- 1 -->
<!-- bArea1 <- 2 -->
<!-- bArea2 <- 3 -->

<!-- e <- rnorm(n-1000, mean=0, sd=10.) -->
<!-- summary(e) -->
<!-- length(e) -->

<!-- e_1000 <- runif(1000, min = 5, max = 200) -->
<!-- summary(e_1000) -->

<!-- e_c <- c(e,e_1000) -->
<!-- length(e_c) -->
<!-- summary(e_c) -->
<!-- summary(e) -->

<!-- y_1000 <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e_c -->

<!-- df_outliers <- data.frame(y_1000, veh_value, gender, veh_age, age_cat, area) -->
<!-- df_outliers[, 'area'] <-  as.factor(df[, 'area']) -->
<!-- df_outliers[, 'gender'] <- as.factor(df[, 'gender']) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- model_outliers <- lm(y ~ veh_value + gender + veh_age + age_cat + area, data=df_outliers) -->
<!-- summary(model_outliers) -->
<!-- plot(model_outliers) -->
<!-- ``` -->



<!-- #Outliers - Vehicle Value -->
<!-- ```{r} -->

<!-- set.seed(103) -->
<!-- n <- 100000 -->
<!-- veh_value <- sample(10:100, n-500, replace=T) -->
<!-- veh_value_500 <- sample(200:700, 500, replace = T) -->
<!-- veh_value <- c(veh_value, veh_value_500) -->

<!-- length(veh_value) -->

<!-- boxplot(veh_value) -->

<!-- gender <- rbinom(n, 1, .5) -->
<!-- veh_age <- sample(0:30, n, replace=T) -->
<!-- age_cat <- sample(25:55, n, replace=T) -->
<!-- area <- sample(0:2, n, replace=T) -->

<!-- b0 <- 10 -->
<!-- b1 <- 5 -->
<!-- b2 <- 3.5 -->
<!-- b3 <- 2 -->
<!-- b4 <- 0.1 -->

<!-- bArea0 <- 1 -->
<!-- bArea1 <- 2 -->
<!-- bArea2 <- 3 -->

<!-- e <- rnorm(n, mean=0, sd=10.) -->
<!-- y <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e -->

<!-- df_vehVal <- data.frame(y, veh_value, gender, veh_age, age_cat, area) -->
<!-- df_vehVal[, 'area'] <-  as.factor(df[, 'area']) -->
<!-- df_vehVal[, 'gender'] <- as.factor(df[, 'gender']) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- model_outliers_vehVal <- lm(y ~ veh_value + gender + veh_age + age_cat + area, data=df_vehVal) -->
<!-- summary(model_outliers_vehVal) -->
<!-- plot(model_outliers_vehVal) -->

<!-- plot(df_vehVal$veh_value,model_outliers_vehVal$residuals) -->
<!-- plot(df_vehVal$veh_age,model_outliers_vehVal$residuals) -->

<!-- ``` -->




<!-- ```{r} -->
<!-- set.seed(100) -->
<!-- n <- 100000 -->
<!-- veh_value <- sample(10:100, n, replace=T) -->
<!-- gender <- rbinom(n, 1, .5) -->
<!-- veh_age <- sample(0:30, n, replace=T) -->
<!-- age_cat <- sample(25:55, n, replace=T) -->
<!-- area <- sample(0:2, n, replace=T) -->

<!-- b0 <- 10 -->
<!-- b1 <- 5 -->
<!-- b2 <- 3.5 -->
<!-- b3 <- 2 -->
<!-- b4 <- 0.1 -->

<!-- bArea0 <- 1 -->
<!-- bArea1 <- 2 -->
<!-- bArea2 <- 3 -->

<!-- e <- rnorm(n, mean=0, sd=10.) -->
<!-- e_replace <- e -->

<!-- y <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e -->

<!-- df <- data.frame(y, veh_value, gender, veh_age, age_cat, area) -->
<!-- df[, 'area'] <-  as.factor(df[, 'area']) -->
<!-- df[, 'gender'] <- as.factor(df[, 'gender']) -->

<!-- e_index <- which(veh_value > 60 & veh_value < 70) -->
<!-- length(e_index) -->


<!-- e_10000 <- runif(length(e_index), min = 5, max = 200) -->
<!-- length(e_10000) -->
<!-- summary(e_10000) -->

<!-- #sample(e_10000,length(e_index)) -->

<!-- e_replace <- replace(e_replace, e_index, e_10000) -->

<!-- length(e) -->
<!-- summary(e) -->

<!-- #head(e_index) -->
<!-- e[c(11,38,45)] -->
<!-- e_replace[c(11,38,45)] -->

<!-- length(e_replace) -->

<!-- summary(e) -->
<!-- summary(e_replace) -->

<!-- mean(veh_value) -->
<!-- median((veh_value)) -->
<!-- sd(veh_value) -->

<!-- hist(veh_value) -->

<!-- y_3 <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e_replace -->

<!-- length(y_3) -->

<!-- df_3 <- data.frame(y_3, veh_value, gender, veh_age, age_cat, area) -->
<!-- df_3[, 'area'] <-  as.factor(df[, 'area']) -->
<!-- df_3[, 'gender'] <- as.factor(df[, 'gender']) -->

<!-- model_outliers_3 <- lm(y_3 ~ veh_value + gender + veh_age + age_cat + area, data=df_3) -->
<!-- summary(model_outliers_3) -->
<!-- plot(model_outliers_3) -->


<!-- summary(model_outliers_3) -->
<!-- plot(veh_value,model_outliers_3$residuals) -->

<!-- # model <- lm(y ~ veh_value + gender + veh_age + age_cat + area, data=df) -->
<!-- # summary(model) -->
<!-- # plot(model) -->
<!-- ``` -->


<!-- # Building no relation model -->
<!-- ```{r} -->
<!-- set.seed(100) -->
<!-- n <- 100000 -->
<!-- veh_value <- sample(10:100, n, replace=T) -->
<!-- gender <- rbinom(n, 1, .5) -->
<!-- veh_age <- sample(0:30, n, replace=T) -->
<!-- age_cat <- sample(25:55, n, replace=T) -->
<!-- area <- sample(0:2, n, replace=T) -->

<!-- b0 <- 0 -->
<!-- b1 <- 0 -->
<!-- b2 <- 0 -->
<!-- b3 <- 0 -->
<!-- b4 <- 0 -->

<!-- bArea0 <- 1 -->
<!-- bArea1 <- 2 -->
<!-- bArea2 <- 3 -->

<!-- e_unif <- runif(n, min = 0 , max = 600) -->

<!-- y_unif <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e_unif -->

<!-- summary(e_unif) -->
<!-- summary(y_unif) -->

<!-- df_4 <- data.frame(y_unif, veh_value, gender, veh_age, age_cat, area) -->
<!-- df_4[, 'area'] <-  as.factor(df[, 'area']) -->
<!-- df_4[, 'gender'] <- as.factor(df[, 'gender']) -->

<!-- model_outliers_4 <- lm(y_unif ~ veh_value + gender + veh_age + age_cat + area, data=df_4) -->
<!-- summary(model_outliers_4) -->
<!-- plot(model_outliers_4) -->

<!-- ``` -->


<!-- #  Non-Normal Distribution  -->
<!-- ```{r} -->
<!-- set.seed(1113) -->
<!-- n <- 10000 -->
<!-- veh_value <- sample(10:100, n, replace=T) -->
<!-- gender <- rbinom(n, 1, .5) -->
<!-- veh_age <- sample(0:30, n, replace=T) -->
<!-- age_cat <- sample(25:55, n, replace=T) -->
<!-- area <- sample(0:2, n, replace=T) -->

<!-- b0 <- 10 -->
<!-- b1 <- 5 -->
<!-- b2 <- 3.5 -->
<!-- b3 <- 2 -->
<!-- b4 <- 0.1 -->

<!-- bArea0 <- 1 -->
<!-- bArea1 <- 2 -->
<!-- bArea2 <- 3 -->

<!-- #exp(1) -->

<!-- #y <- rpois(n,10) -->
<!-- e <- rnorm(n, mean=0, sd=10.) -->

<!-- y <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e -->

<!-- #head(y) -->
<!-- y <- y^2 -->

<!-- df <- data.frame(y, veh_value, gender, veh_age, age_cat, area) -->
<!-- df[, 'area'] <-  as.factor(df[, 'area']) -->
<!-- df[, 'gender'] <- as.factor(df[, 'gender']) -->

<!-- model <- lm(y ~ veh_value + gender + veh_age + age_cat + area, data=df) -->
<!-- summary(model) -->
<!-- plot(model) -->
<!-- hist(model$residuals) -->
<!-- hist(df$y, main = "Response Variable Y - Not normally distributed",xlab='Response Variable') -->
<!-- ``` -->

<!-- Square root transformation using box-cox -->
<!-- ```{r} -->
<!-- library(MASS) -->
<!-- bc <- boxcox(y ~ veh_value + gender + veh_age + age_cat + area,data=df) -->

<!-- (lambda <- bc$x[which.max(bc$y)]) -->
<!-- #  -->
<!-- y_2 <- lm(y^0.5 ~ veh_value + gender + veh_age + age_cat + area, data=df) -->
<!-- summary(y_2) -->
<!-- plot(y_2) -->
<!-- hist(y_2$residuals) -->


<!-- (trans <- bc$x[which.max(bc$y)]) -->
<!-- #[1] 0.4242424 -->
<!-- # re-run with transformation -->
<!-- mnew <- lm(((y^trans-1)/trans) ~  veh_value + gender + veh_age + age_cat + area, data=df) -->
<!-- summary(mnew) -->
<!-- plot(mnew) -->
<!-- ``` -->

<!-- # Y(inverse) transformation -->
<!-- ```{r} -->
<!-- set.seed(1113) -->
<!-- n <- 10000 -->
<!-- veh_value <- sample(10:100, n, replace=T) -->
<!-- gender <- rbinom(n, 1, .5) -->
<!-- veh_age <- sample(0:30, n, replace=T) -->
<!-- age_cat <- sample(25:55, n, replace=T) -->
<!-- area <- sample(0:2, n, replace=T) -->

<!-- b0 <- 10 -->
<!-- b1 <- 5 -->
<!-- b2 <- 3.5 -->
<!-- b3 <- 2 -->
<!-- b4 <- 0.1 -->

<!-- bArea0 <- 1 -->
<!-- bArea1 <- 2 -->
<!-- bArea2 <- 3 -->

<!-- #exp(1) -->

<!-- #y <- rpois(n,10) -->
<!-- e <- rnorm(n, mean=0, sd=10.) -->

<!-- y <- b0 + b1*veh_value + b2*gender + b3*veh_age + b4*age_cat + bArea0 * (area == 0) + bArea1 * (area == 1) + bArea2 * (area == 2) + e -->

<!-- # head(y) -->
<!-- # y[1] -->
<!-- # log(exp(182.8027)) -->

<!-- y <- 1/y -->

<!-- df <- data.frame(y, veh_value, gender, veh_age, age_cat, area) -->
<!-- df[, 'area'] <-  as.factor(df[, 'area']) -->
<!-- df[, 'gender'] <- as.factor(df[, 'gender']) -->

<!-- model <- lm(y ~ veh_value + gender + veh_age + age_cat + area, data=df) -->
<!-- summary(model) -->
<!-- plot(model) -->
<!-- hist(model$residuals) -->


<!-- ``` -->
<!-- ```{r} -->
<!-- library(MASS) -->
<!-- bc <- boxcox(y ~ veh_value + gender + veh_age + age_cat + area,data=df) -->

<!-- (lambda <- bc$x[which.max(bc$y)]) -->
<!-- #  -->
<!-- # y_2 <- lm(y^0.5 ~ veh_value + gender + veh_age + age_cat + area, data=df) -->
<!-- # summary(y_2) -->
<!-- # plot(y_2) -->
<!-- # hist(y_2$residuals) -->


<!-- (trans <- bc$x[which.max(bc$y)]) -->
<!-- #[1] 0.4242424 -->
<!-- # re-run with transformation -->
<!-- mnew <- lm(((y^trans-1)/trans) ~  veh_value + gender + veh_age + age_cat + area, data=df) -->
<!-- summary(mnew) -->
<!-- plot(mnew) -->
<!-- ``` -->

